name: TEFAS Güncellemesi (Otomatik ve Manuel)

on:
  schedule:
    # Türkiye saatiyle 21:26 (UTC 18:26)
    - cron: '31 18 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write 

    steps:
      - name: Depoyu Çek (Checkout)
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: |
          pip install selenium

      - name: Python Kodunu Çalıştır
        run: python main.py

      - name: Değişiklikleri Kaydet ve Gönder
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          if [[ -n $(git status -s) ]]; then
            echo "Değişiklik var, kaydediliyor..."
            git add guncel_fonlar.csv
            git commit -m "Otomatik Güncelleme: Fon Fiyatları"
            git pull --rebase origin main
            git push
          else
            echo "Değişiklik yok."
          fi
