name: Günlük Fon Güncellemesi

# Ne zaman çalışacak?
on:
  schedule:
    # Türkiye saatiyle sabah 10:30 civarı (UTC 07:30)
    - cron: '30 07 * * *'
  # Manuel çalıştırmak için buton koyuyoruz
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fon-verisi-cek:
    runs-on: ubuntu-latest
    
    steps:
    - name: Depoyu Kontrol Et (Checkout)
      uses: actions/checkout@v3

    - name: Python Kurulumu
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Kütüphaneleri Yükle
      run: |
        pip install -r requirements.txt

    - name: Python Kodunu Çalıştır
      run: python main.py

    - name: Değişiklikleri Kaydet (Git Push)
      run: |
        git config --global user.name 'GitHub Action Bot'
        git config --global user.email 'action@github.com'
        git add guncel_fonlar.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik Güncelleme" && git push)
